name: langchain-aws-service
channels:
  - https://conda.anaconda.org/conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
      - aws-cdk-lib
      - boto3
      - chromadb
      - gpt4all
      - langchain==0.0.220
      - langchain_cohere
      - langchain-openai
      - langchainhub
      - langgraph
      - requests
      - tiktoken
